version: "3.9"
services:
  app:
    container_name: $APP_NAME
    image: $APP_NAME
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
    networks:
      - my-network
  db:
    hostname: mongo
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./database:/data
    ports:
      - "27017:27017"
    networks:
      - my-network

networks:
  my-network:
    name: $NETWORK_NAME